{
 "cells": [
  {
   "metadata": {},
   "cell_type": "markdown",
   "source": [
    "# TA-Lib Not Found\n",
    "\n",
    "If you get the following error...\n",
    "\n",
    "```python\n",
    " >   from ._ta_lib import (\n",
    "        _ta_initialize, _ta_shutdown, MA_Type, __ta_version__,\n",
    "        _ta_set_unstable_period as set_unstable_period,\n",
    "        _ta_get_unstable_period as get_unstable_period,\n",
    "        _ta_set_compatibility as set_compatibility,\n",
    "        _ta_get_compatibility as get_compatibility,\n",
    "        __TA_FUNCTION_NAMES__\n",
    "    )\n",
    "E   ImportError: libta_lib.so.0: cannot open shared object file: No such file or directory\n",
    "\n",
    "../../../anaconda3/envs/pricepredict/lib/python3.12/site-packages/talib/__init__.py:109: ImportError\n",
    "```\n",
    "\n",
    "You may need to compile the ta-lib shared library...\n"
   ],
   "id": "bd01f69b4988a33b"
  },
  {
   "metadata": {},
   "cell_type": "markdown",
   "source": [
    "This is the exact same issue we discussed before.\n",
    " \n",
    "### **Explanation:**\n",
    "    1. Dependency: Your Python code, specifically the talib package (which is often a dependency for technical analysis libraries like pandas-ta, used in your pricepredict.py via augment_data), requires the underlying TA-Lib C library.\n",
    "    2. Missing C Library: The error libta_lib.so.0: cannot open shared object file: No such file or directory means your operating system cannot find the compiled C library file (libta_lib.so.0) needed by the talib Python package.\n",
    "    3. Traceback: The error occurs within the talib Python package's initialization (__init__.py), confirming it's failing when trying to load the C library.\n",
    " \n",
    "### **Cause:**\n",
    "The TA-Lib C library is not installed on your system, or if it is, the system cannot locate it. The Python talib package is just a wrapper; it needs the actual C library to function.\n",
    " \n",
    "### **Solution:**\n",
    "You need to install the TA-Lib C library on your operating system before installing the Python talib package.\n",
    "Please refer back to the detailed instructions I provided previously for your specific operating system (Linux/Ubuntu/Debian,  Fedora/CentOS, macOS). The most reliable method is often compiling from source:\n",
    " \n",
    "1. Install build tools (build-essential on Debian/Ubuntu, \"Development Tools\" on Fedora/CentOS).\n",
    "2. Download the ta-lib-0.4.0-src.tar.gz file.\n",
    "3. Extract it (tar -xzf ...).\n",
    "4. Navigate into the ta-lib/ directory.\n",
    "\n",
    "    **Configure, Compile, and Install:**\n",
    "\n",
    "    ```bash\n",
    "    ./configure --prefix=/usr\n",
    "    make\n",
    "    sudo make install\n",
    "    ```\n",
    "6. Update library cache (Linux):\n",
    "\n",
    "    ```bash\n",
    "    sudo ldconfig\n",
    "    ```\n",
    "7. Reinstall the Python wrapper (crucial):\n",
    "\n",
    "    ```bash\n",
    "    pip install --no-cache-dir --force-reinstall TA-Lib\n",
    "    ```\n",
    "    \n",
    "Once the C library is correctly installed and the Python wrapper is reinstalled, this ImportError should be resolved.\n"
   ],
   "id": "bf82083b915c4164"
  },
  {
   "metadata": {},
   "cell_type": "markdown",
   "source": [
    "# Cuda Toolkit Not Found\n",
    "\n",
    "Given the following errors...\n",
    "\n",
    "```bash\n",
    " [*********************100%***********************]  1 of 1 completed\n",
    "I0000 00:00:1744782828.929736  161656 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 7119 MB memory:  -> device: 0, name: NVIDIA RTX A5000 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6\n",
    "2025-04-15 22:53:49.042432: W external/local_xla/xla/service/gpu/llvm_gpu_backend/default/nvptx_libdevice_path.cc:40] Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice. This may result in compilation or runtime failures, if the program we try to run uses routines from libdevice.\n",
    "Searched for CUDA in the following directories:\n",
    "  ./cuda_sdk_lib\n",
    "  pycache_prefix=/home/dsidlo/.cache/JetBrains/PyCharm2024.1/cpython-cache.runfiles/cuda_nvcc\n",
    "  pycache/cuda_nvcc\n",
    "  \n",
    "  /usr/local/cuda\n",
    "  /opt/cuda\n",
    "  /home/dsidlo/anaconda3/envs/pricepredict/lib/python3.12/site-packages/tensorflow/python/platform/../../../nvidia/cuda_nvcc\n",
    "  /home/dsidlo/anaconda3/envs/pricepredict/lib/python3.12/site-packages/tensorflow/python/platform/../../../../nvidia/cuda_nvcc\n",
    "  /home/dsidlo/anaconda3/envs/pricepredict/lib/python3.12/site-packages/tensorflow/python/platform/../../cuda\n",
    "  /home/dsidlo/anaconda3/envs/pricepredict/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../..\n",
    "  /home/dsidlo/anaconda3/envs/pricepredict/lib/python3.12/site-packages/tensorflow/python/platform/../../../../../../..\n",
    "  .\n",
    "You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.\n",
    "2025-04-15 22:53:49.042486: W external/local_xla/xla/service/gpu/llvm_gpu_backend/nvptx_backend.cc:110] libdevice is required by this HLO module but was not found at ./libdevice.10.bc\n",
    "error: libdevice not found at ./libdevice.10.bc\n",
    "...\n",
    ">       q *= tf.sign(d)\n",
    "E       tensorflow.python.framework.errors_impl.UnknownError: {{function_node __wrapped__Sign_device_/job:localhost/replica:0/task:0/device:GPU:0}} JIT compilation failed. [Op:Sign] name:\n",
    "\n",
    "../../../anaconda3/envs/pricepredict/lib/python3.12/site-packages/tf_keras/src/initializers/initializers.py:778: UnknownError\n",
    "``` \n",
    "\n",
    "1. Make sure that the cuda toolkit is installed...\n",
    "    ```bash \n",
    "    apt install nvidia-cuda-toolkit\n",
    "    ```\n",
    "2. Create the symlink **/usr/local/cuda**...\n",
    "    ```bash\n",
    "    ❯ cd /usr/local \n",
    "    ❯ ln -s /usr/lib/cuda/ ./\n",
    "    ```\n",
    "\n",
    "## Note:\n",
    "\n",
    "  - This only works of the nvidia-cuda-toolkit (current Ubuntu package is 11.5.1) package is compatible with the version of tensorflow that you are using.\n",
    "  - I am using tensorflow version 2.19.0 which requires nvidia-cuda-toolkit (ver 12.5)"
   ],
   "id": "c3ce3bce33a5eb69"
  },
  {
   "metadata": {},
   "cell_type": "markdown",
   "source": [
    "# Install the cuda toolkit via conda...\n",
    "\n",
    "  - The following was suggested at: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#driver-installation\n",
    "  - Conda can install the latest required drivers that are compatible with the version of conda that you are running (nvidia-smi)\n",
    "    and the version of tensorflow.\n",
    "    ```bash  \n",
    "    ❯ conda install cuda -c nvidia/label/cuda-12.8.0\n",
    "    ```\n",
    "  - This worked for me.\n",
    " \n"
   ],
   "id": "515936d90f317b75"
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
